version: "3"

services:
  postgres:
    container_name: url_pg_db
    image: postgres
    environment:
      POSTGRES_DB: "url_cutter"
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "pwd123"
    volumes:
      - pg:/var/lib/pg
    ports:
      - 5432:5432

  server:
    container_name: url_cutter_server
    build: .
    networks:
      - default
    depends_on:
      - postgres
    restart: on-failure
    environment:
      APP_NAME: "url_shortener"
      PORT: "8080"
      DB_DSN: "host=postgres user=db_user password=pwd123 dbname=url_cutter port=5432 sslmode=disable"
    ports:
      - 8080:8080
volumes:
  pg: